// Mocks generated by Mockito 5.4.4 from annotations
// in crypto_tracker/test/service/coins_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:crypto_tracker/api/client/coins.dart' as _i2;
import 'package:crypto_tracker/api/data/coins.dart' as _i6;
import 'package:crypto_tracker/model/coin.dart' as _i5;
import 'package:crypto_tracker/model/reference_currency.dart' as _i7;
import 'package:crypto_tracker/service/coins.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCoinsApiClient_0 extends _i1.SmartFake
    implements _i2.CoinsApiClient {
  _FakeCoinsApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CoinsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoinsService extends _i1.Mock implements _i3.CoinsService {
  MockCoinsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CoinsApiClient get coinsApiClient => (super.noSuchMethod(
        Invocation.getter(#coinsApiClient),
        returnValue: _FakeCoinsApiClient_0(
          this,
          Invocation.getter(#coinsApiClient),
        ),
      ) as _i2.CoinsApiClient);

  @override
  set coinsApiClient(_i2.CoinsApiClient? _coinsApiClient) => super.noSuchMethod(
        Invocation.setter(
          #coinsApiClient,
          _coinsApiClient,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<_i5.Coin>> getCoins(
    _i6.CoinsRequestData? requestData,
    _i7.ReferenceCurrency? referenceCurrency,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoins,
          [
            requestData,
            referenceCurrency,
          ],
        ),
        returnValue: _i4.Future<List<_i5.Coin>>.value(<_i5.Coin>[]),
      ) as _i4.Future<List<_i5.Coin>>);

  @override
  List<_i5.Coin> format(
    List<_i5.Coin>? coinsData,
    _i7.ReferenceCurrency? referenceCurrency,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #format,
          [
            coinsData,
            referenceCurrency,
          ],
        ),
        returnValue: <_i5.Coin>[],
      ) as List<_i5.Coin>);

  @override
  int getDecimal(double? price) => (super.noSuchMethod(
        Invocation.method(
          #getDecimal,
          [price],
        ),
        returnValue: 0,
      ) as int);
}
